Перечень того, что надо реализовать.

В качестве основы возьмём https://github.com/NicoNex/echotron 

Для реализации телеграммного фронтэнда нам надо сделать:
* Переделать layout
  - [X] На гошный

* Парсер конфига.
  - [X] Реализован начальный вариант парсера конфига.

* Разгребальщик апдейтов и формирователь redis-ных сообщений.
  - [X] Написана заглушка для парсера апдейтов bot api телеграма
  - [X] Написан парсер прочих команд

* Разгребальщик редисных сообщений и формирователь запросов в tg bot api.
  - [X] Написан черновой вариант разгребателя
  - [ ] Написан мигратор для группового чата. (апгрейд до супергруппы, до чата с тредами)

* Обработчик группы команд admin, сохранение настроек в pebbledb.
  - [X] [X] цензор сообщений определённого типа.
  - [X] [X] фортунка каждое утро. См. п.13.
  - [X] [X] Приветствие новых участников
  - [X] [X] Прощание с теми, кто ушёл
  - [ ] [ ] oboobs
  - [ ] [ ] obutts
  - [X] [X] chan_msg (Пока что бот сам удяляет сообщения от таких имперсонализированных пользователей, однако в прроде
            есть возможность таких персонажей банить, см banChatSenderChat()/unbanChatSenderChat()
            https://core.telegram.org/bots/api#banchatsenderchat, надо ли реализовывать такой бан - над этим надо ещё
            подумать.)
  - [ ] [ ] user ban
  - [ ] [ ] user mute

* help
  - [X] done

* help admin
  - [X] done

* Написать README.md
  - [ ] done

* Поддержать миграцию групп в супергруппы (итд, там меняется id и надо перекидывать настройки на новый id)
  - [ ] done

* Поддержать парсинг ошибок отправки сообщений в телегу (в т.ч. мигратор для группового чата, также внятные сообщения в лог, если бот замьючен)
  - [ ] done

* Поддержать leaveChat(), чтобы бот мог легально и самостоятельно покинуть чят.
  - [ ] done

* Cтавить реакцию thumbsup на спасибо, пожалуйста итд, ставить сердечко, если похвалили - молодц, красава итд. (setMessageReaction() на соответствующий ответ на сообщение)
  - [ ] done

* Отслеживать участников чятика, чтобы была возможность мьютить, банить, узнавать инфу по разным участникам чятика.
  - [ ] done

* Промоут/демоут участника до админа
  - [ ] done

* Cron-like "сервис". Он нужен для
  - [ ] отправки приветствий по утрам.
  - [V] регулярных компакций базы с настройками.
  - [ ] регулярного обслуживания таблиц с пользователями.

* В функции AppendChatListDB для нового чата добавлять дефолтные значения настроек.
  - [ ] done

# -*- mode: org; -*-
# vim: ft=org
